name: 🤖 CI Run SanityTest Execution 🧪
run-name: ${{ github.actor }} 👨🏻‍🔬 ran SanityTest in ${{ github.ref_name }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  SanityTest:
    runs-on: ubuntu-latest
    environment: CI-Testing # 🔹 Aquí usamos el Environment creado en GitHub

    steps:
      - name: 💻 Checkout Repository
        uses: actions/checkout@v3

      - name: 💿 Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.5'

      - name: 🧬 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Instalar pytest manualmente

      - name: 🧪 Run Selenium Tests with Pytest
        env:
          SWL_USERNAME: ${{ vars.SWL_USERNAME }} # Se obtiene desde el Environment "CI-Testing"
          SWL_PASSWORD: ${{ vars.SWL_PASSWORD }}
        run: |
          if [[ -z "$SWL_USERNAME" || -z "$SWL_PASSWORD" ]]; then
            echo "❌ ERROR: Variables de entorno no definidas en GitHub."
            exit 1
          fi
          pytest tests/ --disable-warnings
